### ISSUE TITLE
I can't pull the image

### ISSUE THREAD

**Issue by sfeng13** [ShuoYangRobotics/Cerberus#20]
[139580 ms] Start: Run: docker pull yyss2028/legged_state_estimation:1.0
1.0: Pulling from yyss2028/legged_state_estimation
11323ed2c653: Pulling fs layer 
5ed186fe30ca: Pulling fs layer 
fac38668a25e: Pulling fs layer 
3121bbb0fedc: Waiting 
c74eff7c67bd: Pulling fs layer 
c74eff7c67bd: Waiting 
f141a0064ed4: Waiting 
6519125a60ec: Pulling fs layer 
26e5e41cd901: Waiting 
02602ee04379: Pulling fs layer 
6519125a60ec: Waiting 
744d91d71b38: Waiting 
63360092ca0d: Waiting 
644b19d25198: Waiting 
b65f20739a63: Pulling fs layer 
0f55deb24ad8: Pulling fs layer 
debe48143393: Waiting 
d0586046afad: Waiting 
0f55deb24ad8: Waiting 
c27f7231b2c8: Pulling fs layer 
f681c35bbabc: Pulling fs layer 
f9de07663faa: Pulling fs layer 
73a79b2e01d9: Pulling fs layer 
b65f20739a63: Waiting 
b20dc4c89960: Waiting 
8a03e801ed03: Waiting 
b9fc71c01fce: Waiting 
e02806be1546: Waiting 
5126f9061b09: Waiting 
417c37172e85: Waiting 
34750f33aa9f: Waiting 
1d697f8b29e9: Waiting 
f8de90ef3221: Waiting 
08232ae31b21: Waiting 
083dc6562cf3: Waiting 
error pulling image configuration: download failed after attempts=6: dial tcp 64.13.192.74:443: i/o timeout
[301594 ms] []
[301594 ms] Error response from daemon: No such image: yyss2028/legged_state_estimation:1.0

[301596 ms] Error: Command failed: docker inspect --type image yyss2028/legged_state_estimation:1.0
[301596 ms]     at ptA (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:465:1260)
[301596 ms]     at NH (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:465:1002)
[301596 ms]     at async KtA (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:482:3771)
[301596 ms]     at async eB (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:482:4886)
[301596 ms]     at async hrA (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:663:200)
[301596 ms]     at async lrA (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:662:13452)
[301604 ms] Exit code 1
[301611 ms] Command failed: /snap/code/165/usr/share/code/code /home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/zwt/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-91da1381-6db1-4ed8-894c-e05c9a8d25a31723704655008 --workspace-folder /home/zwt/Cerberus --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/zwt/Cerberus --id-label devcontainer.config_file=/home/zwt/Cerberus/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/zwt/Cerberus/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[301611 ms] Exit code 1

**Comment by sfeng13** [comment]
[139580 ms] Start: Run: docker pull yyss2028/legged_state_estimation:1.0
1.0: Pulling from yyss2028/legged_state_estimation
11323ed2c653: Pulling fs layer 
5ed186fe30ca: Pulling fs layer 
fac38668a25e: Pulling fs layer 
3121bbb0fedc: Waiting 
c74eff7c67bd: Pulling fs layer 
c74eff7c67bd: Waiting 
f141a0064ed4: Waiting 
6519125a60ec: Pulling fs layer 
26e5e41cd901: Waiting 
02602ee04379: Pulling fs layer 
6519125a60ec: Waiting 
744d91d71b38: Waiting 
63360092ca0d: Waiting 
644b19d25198: Waiting 
b65f20739a63: Pulling fs layer 
0f55deb24ad8: Pulling fs layer 
debe48143393: Waiting 
d0586046afad: Waiting 
0f55deb24ad8: Waiting 
c27f7231b2c8: Pulling fs layer 
f681c35bbabc: Pulling fs layer 
f9de07663faa: Pulling fs layer 
73a79b2e01d9: Pulling fs layer 
b65f20739a63: Waiting 
b20dc4c89960: Waiting 
8a03e801ed03: Waiting 
b9fc71c01fce: Waiting 
e02806be1546: Waiting 
5126f9061b09: Waiting 
417c37172e85: Waiting 
34750f33aa9f: Waiting 
1d697f8b29e9: Waiting 
f8de90ef3221: Waiting 
08232ae31b21: Waiting 
083dc6562cf3: Waiting 
error pulling image configuration: download failed after attempts=6: dial tcp 64.13.192.74:443: i/o timeout
[301594 ms] []
[301594 ms] Error response from daemon: No such image: yyss2028/legged_state_estimation:1.0

[301596 ms] Error: Command failed: docker inspect --type image yyss2028/legged_state_estimation:1.0
[301596 ms]     at ptA (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:465:1260)
[301596 ms]     at NH (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:465:1002)
[301596 ms]     at async KtA (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:482:3771)
[301596 ms]     at async eB (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:482:4886)
[301596 ms]     at async hrA (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:663:200)
[301596 ms]     at async lrA (/home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js:662:13452)
[301604 ms] Exit code 1
[301611 ms] Command failed: /snap/code/165/usr/share/code/code /home/zwt/.vscode/extensions/ms-vscode-remote.remote-containers-0.380.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/zwt/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-91da1381-6db1-4ed8-894c-e05c9a8d25a31723704655008 --workspace-folder /home/zwt/Cerberus --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/zwt/Cerberus --id-label devcontainer.config_file=/home/zwt/Cerberus/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/zwt/Cerberus/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[301611 ms] Exit code 1
